trigger:
  - main

variables:
  pythonVersion: '3.12'
  webAppName: 'prediction-time-api-v1'
  environmentName: 'production'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
        architecture: 'x64'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    # Create deployment script
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $deployScript = @"
          cd /home/site/wwwroot
          pip install -r requirements.txt
          "@
          $deployScript | Out-File -FilePath "$(Build.ArtifactStagingDirectory)\startup.sh" -Encoding UTF8
      displayName: 'Create deployment script'

    # Copy necessary files for deployment
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.py
          requirements.txt
          .env.example
          features/.gitkeep
          training_data/.gitkeep
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy deployment files'

    # Archive the files
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
      displayName: 'Archive files'

    # Publish the artifact
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish artifact'

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'PredictionTimeAzure'  # Update this
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              startUpCommand: 'pip install -r requirements.txt && gunicorn --bind=0.0.0.0 --timeout 600 app:app'